apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
      - name: invoice
        image: techs129/innovative-ci-invoice-service:latest
        ports:
        - containerPort: 5050  # Updated port
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: PORT
          value: "5050"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice
  ports:
  - port: 5050
    targetPort: 5050
