apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: techs129/innovative-ci-payment-service:latest
        ports:
        - containerPort: 6060  # Changed to browser-safe port
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: PORT
          value: "6060"
        - name: NODE_ENV
          value: "production"
        - name: INVOICE_URL
          value: "http://invoice-service:5050"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - port: 6060
    targetPort: 6060
