apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: supersecretdevops
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: host.docker.internal
  DB_PORT: "5432"
  DB_NAME: invoicedb
  DB_USER: postgres
  DB_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: invoicedb
  JWT_SECRET: supersecretdevops
  DB_HOST: host.docker.internal
  DB_PORT: "5432"
  DB_NAME: invoicedb
  DB_USER: postgres
  DB_PASSWORD: postgres
  KAFKA_BROKERS: host.docker.internal:9092
